### ISSUE TITLE
Error on pystac_client Client import since v0.4.0

### ISSUE THREAD

**Issue by orilevari** [stac-utils/pystac-client#239]
Since my project updated to using pystac-client 0.4.0, I get the following stack trace when importing pystac-client.Client:

```Traceback (most recent call last):
  ...
    from pystac_client import Client

  File "/usr/local/lib/python3.8/site-packages/pystac_client/__init__.py", line 3, in <module>
    from pystac_client.client import Client

  File "/usr/local/lib/python3.8/site-packages/pystac_client/client.py", line 8, in <module>
    from pystac_client.collection_client import CollectionClient

  File "/usr/local/lib/python3.8/site-packages/pystac_client/collection_client.py", line 7, in <module>
    from pystac_client.item_search import ItemSearch

  File "/usr/local/lib/python3.8/site-packages/pystac_client/item_search.py", line 17, in <module>
    from pystac_client.stac_api_io import StacApiIO

  File "/usr/local/lib/python3.8/site-packages/pystac_client/stac_api_io.py", line 31, in <module>
    class StacApiIO(DefaultStacIO):

  File "/usr/local/lib/python3.8/site-packages/pystac_client/stac_api_io.py", line 57, in StacApiIO
    def read_text(self, source: pystac.link.HREF, *args: Any, **kwargs: Any) -> str:

AttributeError: module 'pystac.link' has no attribute 'HREF'
```

I believe this bug originates from this PR: https://github.com/stac-utils/pystac-client/pull/229 due to the change in function definition to read_text in stac_api_io.py, although I am not familiar with why this attribute would not be resolving.

For now I am pinning my version to v0.3.5, but I thought I'd just create this issue so that it can get addressed quickly since I imagine this is impacting others who haven't pinned their versions.

Thanks!

**Comment by gadomski** [comment]
Can you provide some additional context, including
- `pystac` and `pystac-client` versions
- the code you're trying to execute, reduced if possible to the least amount of code required to reproduce the error.

I am unable to reproduce:
```shell
$ mkvirtualenv pystac-client-issues-239 >/dev/null 2>/dev/null && pip install pystac-client >/dev/null 2>/dev/null
$  pip freeze | grep pystac
pystac==1.4.0
pystac-client==0.4.0
$ python -c "from pystac_client import Client"
$
```

**Comment by TomAugspurger** [comment]
This error message is consistent with having pystac-client==0.4.0 and pystac==1.3.0.

pystac-client correctly specifies a requirement on pystac>=1.4.0

```python
❯ pip install pystac-client==0.4.0 pystac==1.3.0
Collecting pystac-client==0.4.0
  Using cached pystac_client-0.4.0-py3-none-any.whl (24 kB)
Collecting pystac==1.3.0
  Using cached pystac-1.3.0-py3-none-any.whl (133 kB)
Collecting requests>=2.25
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
ERROR: Cannot install pystac-client==0.4.0 and pystac==1.3.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pystac==1.3.0
    pystac-client 0.4.0 depends on pystac>=1.4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

But you can still end up in this state if you have pystac 1.3.0 and then install pystac-client into the environment.

**Comment by TomAugspurger** [comment]
Agreed, no action needed.
