### ISSUE TITLE
Can not import 'API'

### ISSUE THREAD

**Issue by YifanZhao0822** [stac-utils/pystac-client#69]
Hi,

Apologies if this is a dull question. But I can't find any solution or workaround elsewhere.

I was trying the example in the docs: https://pystac-client.readthedocs.io/en/latest/usage/stac_api.html

But encountered errors in the very beginning. Please see below:

>>> from pystac_client.Client import API
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pystac_client.Client'

And:

>>> from pystac_client import API
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'API' from 'pystac_client' (/Applications/anaconda3/envs/deep/lib/python3.8/site-packages/pystac_client/__init__.py)

I tried it on both the base and virtual envs but they have the same error message. 

The pystac-client package was installed by the command in doc: pip install git+https://github.com/stac-utils/pystac-client.git#egg=pystac_client

My python version is 3.7

Can someone help me with this issue? Appreciate it.

**Comment by p1d1d1** [comment]
same here

**Comment by duckontheweb** [comment]
The `API` class was renamed to `Client` in 10c2021ca07fd30417aa5ddcf6e6e6d1f0d8591e, but it looks like the documentation is out of date. Does replacing all instances of `API` with `Client` solve the problem?

**Comment by p1d1d1** [comment]
Examples in docu do not work for me.

**Comment by duckontheweb** [comment]
Okay, so it actually looks like there are a number of issues with that example:

* `from pystac_client.Client import API` should be `from pystac_client import Client`
* `Client.from_file('https://eod-catalog-svc-prod.astraea.earth')` raises a `NotImplementedError`:
    
    ```python
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/jduckworth/.pyenv/versions/pystac-client-dev/lib/python3.8/site-packages/pystac/catalog.py", line 961, in from_file
        result = super().from_file(href, stac_io)
      File "/Users/jduckworth/.pyenv/versions/pystac-client-dev/lib/python3.8/site-packages/pystac/stac_object.py", line 476, in from_file
        o = cls.from_dict(d, href=href, migrate=True, preserve_dict=False)
      File "/Users/jduckworth/Code/stac/pystac-client/pystac_client/client.py", line 127, in from_dict
        cat = cls(id=id,
      File "/Users/jduckworth/Code/stac/pystac-client/pystac_client/client.py", line 56, in __init__
        self.conforms_to(ConformanceClasses.CORE)
      File "/Users/jduckworth/Code/stac/pystac-client/pystac_client/conformance.py", line 89, in conforms_to
        raise NotImplementedError(f"{conformance_class} not supported")
    NotImplementedError: ConformanceClasses.CORE not supported
    ```
It looks like the cause of the conformance failure is the fact that the Astraea API uses `http://` for its conformance URIs and `pystac_client` [only checks for `https://` URIs](https://github.com/stac-utils/pystac-client/blob/6a2d8d8784ac0d1a6861a5dc5d955bfcef6af304/pystac_client/conformance.py#L33).

cc: @matthewhanson @philvarner

**Comment by philvarner** [comment]
One difference here is that OGC API conformance classes are `http` whereas STAC are all `https`. This really just a string and not a URL. I think the right way to handle this is:

1) STAC API defines that the CCs use https
2) The Validator will only validate with https, and return a warning if http CCs exist (a warning instead of an error so that APIs could include both for backwards compatibility)
3) Pystac-client can support either (Postel's Law), since otherwise, it won't work against APIs that are out of compliance but the user has no control over.

Thoughts?

**Comment by YifanZhao0822** [comment]
'from pystac_client import Client' works. Thanks @duckontheweb 

I tried http but it's returning with the same error message:

```
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/deep/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-110-2b8566dc4b6a>", line 1, in <module>
    api = Client.from_file(url)
  File "/Applications/anaconda3/envs/deep/lib/python3.8/site-packages/pystac/catalog.py", line 961, in from_file
    result = super().from_file(href, stac_io)
  File "/Applications/anaconda3/envs/deep/lib/python3.8/site-packages/pystac/stac_object.py", line 476, in from_file
    o = cls.from_dict(d, href=href, migrate=True, preserve_dict=False)
  File "/Applications/anaconda3/envs/deep/lib/python3.8/site-packages/pystac_client/client.py", line 127, in from_dict
    cat = cls(id=id,
  File "/Applications/anaconda3/envs/deep/lib/python3.8/site-packages/pystac_client/client.py", line 56, in __init__
    self.conforms_to(ConformanceClasses.CORE)
  File "/Applications/anaconda3/envs/deep/lib/python3.8/site-packages/pystac_client/conformance.py", line 89, in conforms_to
    raise NotImplementedError(f"{conformance_class} not supported")
NotImplementedError: ConformanceClasses.CORE not supported
```

Any other possible workarounds for this issue? Thanks

**Comment by philvarner** [comment]
The underlying issue is that EOD uses the wrong conformance classes -- e.g., `http://stacspec.org/spec/api/1.0.0-beta.1/req/stac-search` instead of `https://api.stacspec.org/v1.0.0-beta.2/item-search`

**Comment by YifanZhao0822** [comment]
In this case, how should I change the corresponding configuration? Thanks

**Comment by matthewhanson** [comment]
Conformance Classes are possibly one issue, but the other is that you need to use `Client.open(url)` rather than `Client.from_file(url)`.  
The open function initializes the StacApiIO class that is needed for interacting with APIs

**Comment by matthewhanson** [comment]
For the conformance classes, I'm adding in the option to ignore the conformance classes advertised so that you'll be able to open it anyway, it's just that some functionality may cause errors if the API doesn't support it.
